### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by ka-jun** [ka-jun/protospace-33834#2]
#URL
https://protospace-33834.herokuapp.com/

**Comment by kouhei-masuda** [comment]
@ka-jun さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・画像なしで投稿しようとしたところ、下記のエラー画面になりトップページも表示できなくなった。
(※本来は投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まる仕様になります。)

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

<img width="1186" alt="スクリーンショット 2021-03-27 18 22 53" src="https://user-images.githubusercontent.com/53155744/112716415-b222fa80-8f29-11eb-84ef-294b4be41280.png">

**Comment by ka-jun** [comment]
ご指摘いただいた箇所を修正いたしました。
お手数ですが再度、ご確認のほどよろしくお願いいたします。

**Comment by kouhei-masuda** [comment]
@ka-jun さん、再度のご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・トップページにアクセスしようとするとエラーが起きてアクセスできない

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by ka-jun** [comment]
確認漏れがあり、失礼いたしました。
修正しましたので、ご確認をお願いいたします。

**Comment by genki-inoue-div** [comment]
@ka-jun 
寺口さんおつかれさまです！
朝早くから修正ありがとうございます！

達成要件のなかに、修正点が１点ございます。
`ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できること`

上記の修正箇所が原因で、動作未確認の項目が以下です。
```
・コメント投稿欄は、ログイン状態のユーザーへのみ、詳細ページに表示されていること
・ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること
・ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、
　そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること
・ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・
　ユーザー新規登録ページ・ログインページには遷移できること
```

おそらくリダイレクトが全てのページへの遷移にかかってしまっているので、
トップページとプロトタイプ詳細ページとユーザー詳細ページへのリダイレクト処理をのぞいて上げるだけでよろしいかと思います。お手数ですが、あと少しです！修正のほどよろしくお願いいたします！

**Comment by ka-jun** [comment]
ご確認ありがとうございました。
ログアウト状態でも閲覧可能にしましたので、再度ご確認をお願いいたします。

**Comment by genki-inoue-div** [comment]
@ka-jun  
寺口さん
ご修正ありがとうございます！
上記修正点、他実装機能につきましても
問題なく正常に動作することが確認できました！
　
LGTMです！！
おめでとうございます🎉
よくぞ乗り越えていただきました。
次はいよいよ最終課題ですね！

今まで学習したことを活かして進めていきましょう！
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちくださいませ！☺️
